BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `tags` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS `people` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS `events_tags` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`event_id`	INTEGER NOT NULL,
	`tag_id`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `events_people` (
	`event_id`	INTEGER NOT NULL,
	`person_id`	INTEGER NOT NULL,
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	FOREIGN KEY(`person_id`) REFERENCES `people`(`id`),
	FOREIGN KEY(`event_id`) REFERENCES `events`(`id`)
);
CREATE TABLE IF NOT EXISTS `events` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`description`	TEXT,
	`created_at`	TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
